# Define vectors to store draws
saveRDS(est_tot_consumption_1,"Results/scenario1/est_tot_consumption_1.RDS")
saveRDS(est_mean_frequency_1,"Results/scenario1/est_mean_frequency_1.RDS")
saveRDS(est_mean_consprob_1,"Results/scenario1/est_mean_consprob_1.RDS")
saveRDS(est_a2_1_1,"Results/scenario1/est_a2_1_1.RDS")
saveRDS(est_a2_2_1,"Results/scenario1/est_a2_2_1.RDS")
saveRDS(est_a2_3_1,"Results/scenario1/est_a2_3_1.RDS")
saveRDS(est_a3_1_1,"Results/scenario1/est_a3_1_1.RDS")
saveRDS(est_a3_2_1,"Results/scenario1/est_a3_2_1.RDS")
saveRDS(est_b2_1_1,"Results/scenario1/est_b2_1_1.RDS")
saveRDS(est_b2_2_1,"Results/scenario1/est_b2_2_1.RDS")
saveRDS(est_b2_3_1,"Results/scenario1/est_b2_3_1.RDS")
saveRDS(est_b3_1_1,"Results/scenario1/est_b3_1_1.RDS")
saveRDS(est_b3_2_1,"Results/scenario1/est_b3_2_1.RDS")
saveRDS(est_c2_1_1,"Results/scenario1/est_c2_1_1.RDS")
saveRDS(est_c2_2_1,"Results/scenario1/est_c2_2_1.RDS")
saveRDS(est_c2_3_1,"Results/scenario1/est_c2_3_1.RDS")
saveRDS(est_c3_1,"Results/scenario1/est_c3_1.RDS")

saveRDS(sim_tot_consumption_1,"Results/scenario1/sim_tot_consumption_1.RDS")
saveRDS(sim_mean_frequency_1,"Results/scenario1/sim_mean_frequency_1.RDS")
saveRDS(sim_mean_consprob_1,"Results/scenario1/sim_mean_consprob_1.RDS")