# Define vectors to store draws
saveRDS(est_tot_consumption_2,"Results/scenario2/est_tot_consumption_2.RDS")
saveRDS(est_mean_frequency_2,"Results/scenario2/est_mean_frequency_2.RDS")
saveRDS(est_mean_consprob_2,"Results/scenario2/est_mean_consprob_2.RDS")
saveRDS(est_a2_1_2,"Results/scenario2/est_a2_1_2.RDS")
saveRDS(est_a2_2_2,"Results/scenario2/est_a2_2_2.RDS")
saveRDS(est_a2_3_2,"Results/scenario2/est_a2_3_2.RDS")
saveRDS(est_a3_1_2,"Results/scenario2/est_a3_1_2.RDS")
saveRDS(est_a3_2_2,"Results/scenario2/est_a3_2_2.RDS")
saveRDS(est_b2_1_2,"Results/scenario2/est_b2_1_2.RDS")
saveRDS(est_b2_2_2,"Results/scenario2/est_b2_2_2.RDS")
saveRDS(est_b2_3_2,"Results/scenario2/est_b2_3_2.RDS")
saveRDS(est_b3_1_2,"Results/scenario2/est_b3_1_2.RDS")
saveRDS(est_b3_2_2,"Results/scenario2/est_b3_2_2.RDS")
saveRDS(est_c2_1_2,"Results/scenario2/est_c2_1_2.RDS")
saveRDS(est_c2_2_2,"Results/scenario2/est_c2_2_2.RDS")
saveRDS(est_c2_3_2,"Results/scenario2/est_c2_3_2.RDS")
saveRDS(est_c3_2,"Results/scenario2/est_c3_2.RDS")

saveRDS(sim_tot_consumption_2,"Results/scenario2/sim_tot_consumption_2.RDS")
saveRDS(sim_mean_frequency_2,"Results/scenario2/sim_mean_frequency_2.RDS")
saveRDS(sim_mean_consprob_2,"Results/scenario2/sim_mean_consprob_2.RDS")