# Define vectors to store draws
saveRDS(est_tot_consumption_3,"Results/scenario3/est_tot_consumption_3.RDS")
saveRDS(est_mean_frequency_3,"Results/scenario3/est_mean_frequency_3.RDS")
saveRDS(est_mean_consprob_3,"Results/scenario3/est_mean_consprob_3.RDS")
saveRDS(est_a2_1_3,"Results/scenario3/est_a2_1_3.RDS")
saveRDS(est_a2_2_3,"Results/scenario3/est_a2_2_3.RDS")
saveRDS(est_a2_3_3,"Results/scenario3/est_a2_3_3.RDS")
saveRDS(est_a3_1_3,"Results/scenario3/est_a3_1_3.RDS")
saveRDS(est_a3_2_3,"Results/scenario3/est_a3_2_3.RDS")
saveRDS(est_b2_1_3,"Results/scenario3/est_b2_1_3.RDS")
saveRDS(est_b2_2_3,"Results/scenario3/est_b2_2_3.RDS")
saveRDS(est_b2_3_3,"Results/scenario3/est_b2_3_3.RDS")
saveRDS(est_b3_1_3,"Results/scenario3/est_b3_1_3.RDS")
saveRDS(est_b3_2_3,"Results/scenario3/est_b3_2_3.RDS")
saveRDS(est_c2_1_3,"Results/scenario3/est_c2_1_3.RDS")
saveRDS(est_c2_2_3,"Results/scenario3/est_c2_2_3.RDS")
saveRDS(est_c2_3_3,"Results/scenario3/est_c2_3_3.RDS")
saveRDS(est_c3_3,"Results/scenario3/est_c3_3.RDS")

saveRDS(sim_tot_consumption_3,"Results/scenario3/sim_tot_consumption_3.RDS")
saveRDS(sim_mean_frequency_3,"Results/scenario3/sim_mean_frequency_3.RDS")
saveRDS(sim_mean_consprob_3,"Results/scenario3/sim_mean_consprob_3.RDS")